### ISSUE TITLE
Not run

### ISSUE THREAD

**Issue by vietnux** [stionic/com-stionic-facebookads#3]
Not run 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.andro
id.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.an
droid.desugar.Desugar with arguments {--input D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\tr
ansforms\stackFramesFixer\debug\6.jar --output D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\t
ransforms\desugar\debug\5.jar --input D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transforms
\stackFramesFixer\debug\28.jar --output D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transfor
ms\desugar\debug\17.jar --input D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\classes\debug --
output D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transforms\desugar\debug\1 --input D:\www
\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\33.jar --output D:\w
ww\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transforms\desugar\debug\22.jar --input D:\www\html5
\truyenxuatichcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\18.jar --output D:\www\htm
l5\truyenxuatichcu\platforms\android\app\build\intermediates\transforms\desugar\debug\7.jar --input D:\www\html5\truyen
xuatichcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\37.jar --output D:\www\html5\truy
enxuatichcu\platforms\android\app\build\intermediates\transforms\desugar\debug\26.jar --input D:\www\html5\truyenxuatic
hcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\26.jar --output D:\www\html5\truyenxuat
ichcu\platforms\android\app\build\intermediates\transforms\desugar\debug\15.jar --input D:\www\html5\truyenxuatichcu\pl
atforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\38.jar --output D:\www\html5\truyenxuatichcu\
platforms\android\app\build\intermediates\transforms\desugar\debug\27.jar --input D:\www\html5\truyenxuatichcu\platform
s\android\app\build\intermediates\transforms\stackFramesFixer\debug\23.jar --output D:\www\html5\truyenxuatichcu\platfo
rms\android\app\build\intermediates\transforms\desugar\debug\12.jar --input D:\www\html5\truyenxuatichcu\platforms\andr
oid\app\build\intermediates\transforms\stackFramesFixer\debug\5.jar --output D:\www\html5\truyenxuatichcu\platforms\and
roid\app\build\intermediates\transforms\desugar\debug\4.jar --classpath_entry D:\www\html5\truyenxuatichcu\platforms\an
droid\CordovaLib\build\intermediates\intermediate-jars\debug\classes.jar --classpath_entry D:\www\html5\truyenxuatichcu
\platforms\android\app\build\intermediates\classes\debug --classpath_entry D:\www\html5\truyenxuatichcu\platforms\andro
id\app\build\intermediates\transforms\stackFramesFixer\debug\0.jar --classpath_entry D:\www\html5\truyenxuatichcu\platf
orms\android\app\build\intermediates\transforms\stackFramesFixer\debug\1.jar --classpath_entry D:\www\html5\truyenxuati
chcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\5.jar --classpath_entry D:\www\html5\t
ruyenxuatichcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\6.jar --classpath_entry D:\w
ww\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\17.jar --classpath
_entry D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\18.jar
--classpath_entry D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\de
bug\19.jar --classpath_entry D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transforms\stackFra
mesFixer\debug\20.jar --classpath_entry D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transfor
ms\stackFramesFixer\debug\21.jar --classpath_entry D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediat
es\transforms\stackFramesFixer\debug\22.jar --classpath_entry D:\www\html5\truyenxuatichcu\platforms\android\app\build\
intermediates\transforms\stackFramesFixer\debug\23.jar --classpath_entry D:\www\html5\truyenxuatichcu\platforms\android
\app\build\intermediates\transforms\stackFramesFixer\debug\24.jar --classpath_entry D:\www\html5\truyenxuatichcu\platfo
rms\android\app\build\intermediates\transforms\stackFramesFixer\debug\25.jar --classpath_entry D:\www\html5\truyenxuati
chcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\26.jar --classpath_entry D:\www\html5\
truyenxuatichcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\27.jar --classpath_entry D:
\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\28.jar --classpa
th_entry D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\29.ja
r --classpath_entry D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\
debug\30.jar --classpath_entry D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transforms\stackF
ramesFixer\debug\31.jar --classpath_entry D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transf
orms\stackFramesFixer\debug\32.jar --classpath_entry D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermedi
ates\transforms\stackFramesFixer\debug\33.jar --classpath_entry D:\www\html5\truyenxuatichcu\platforms\android\app\buil
d\intermediates\transforms\stackFramesFixer\debug\34.jar --classpath_entry D:\www\html5\truyenxuatichcu\platforms\andro
id\app\build\intermediates\transforms\stackFramesFixer\debug\35.jar --classpath_entry D:\www\html5\truyenxuatichcu\plat
forms\android\app\build\intermediates\transforms\stackFramesFixer\debug\36.jar --classpath_entry D:\www\html5\truyenxua
tichcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\37.jar --classpath_entry D:\www\html
5\truyenxuatichcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\38.jar --classpath_entry
D:\www\html5\truyenxuatichcu\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\39.jar --bootc
lasspath_entry D:\MyJobs\AVDAndroid\platforms\android-27\android.jar --bootclasspath_entry D:\MyJobs\AVDAndroid\platfor
ms\android-27\optional\org.apache.http.legacy.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_172\jre\lib\reso
urces.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_172\jre\lib\rt.jar --bootclasspath_entry C:\Program File
s\Java\jdk1.8.0_172\jre\lib\jsse.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_172\jre\lib\jce.jar --bootcla
sspath_entry C:\Program Files\Java\jdk1.8.0_172\jre\lib\charsets.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8
.0_172\jre\lib\jfr.jar --min_sdk_version 19 --nodesugar_try_with_resources_if_needed --desugar_try_with_resources_omit_
runtime_classes}

**Comment by vietnux** [comment]
BUILD FAILED in 12s
cmd: Command failed with exit code 1 Error output:
Exception in thread "main" java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodCla
ssFixer.java:471)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFi
xer.java:319)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:88)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:85)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:150)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)
